// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var BsAsync = require("../src/bsAsync.js");

function unlink(path, cb) {
  Fs.unlink(path, (function (exn) {
          if (exn == null) {
            return BsAsync.Callback[/* return */2](/* () */0, cb);
          } else {
            return BsAsync.Callback[/* fail */3](exn, cb);
          }
        }));
  return /* () */0;
}

function unlink_if_fopen(path) {
  return BsAsync.Callback[/* >> */5]((function (param) {
                Fs.open(path, param);
                return /* () */0;
              }), (function () {
                return (function (param) {
                    return unlink(path, param);
                  });
              }));
}

function Fs_000(prim, prim$1) {
  Fs.open(prim, prim$1);
  return /* () */0;
}

var Fs$1 = [
  Fs_000,
  unlink
];

exports.Fs = Fs$1;
exports.unlink_if_fopen = unlink_if_fopen;
/* fs Not a pure module */
