// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var BsCallback = require("../src/bsCallback.js");

function unlink(path, cb) {
  Fs.unlink(path, (function (exn) {
          if (exn == null) {
            return BsCallback.$$return(/* () */0, cb);
          } else {
            return BsCallback.fail(exn, cb);
          }
        }));
  return /* () */0;
}

function unlink_if_fopen(path) {
  return BsCallback.$great$great((function (param) {
                Fs.open(path, param);
                return /* () */0;
              }), (function () {
                return (function (param) {
                    return unlink(path, param);
                  });
              }));
}

function Fs_000(prim, prim$1) {
  Fs.open(prim, prim$1);
  return /* () */0;
}

var Fs$1 = [
  Fs_000,
  unlink
];

exports.Fs = Fs$1;
exports.unlink_if_fopen = unlink_if_fopen;
/* fs Not a pure module */
